#! /bin/bash
# To pre & post check servers
#
echo ""
read -p "	Pre-check (1) or Post-check (2)? [1 or 2] " ans

if [ $ans == "1" ]
then
echo ""

# Reading CRQ Number

read -p "	Please enter the CRQ number? : " CRQ 
echo ""

echo "	Started Pre-checks ..."
echo ""

file1=/software/hit/scripts/tr/bios_helper.sh 
file2=/software/hit/scripts/tr/TR-Server-Report.sh

for s in `cat hosts_list`
do
echo -e "	Sending bios_helper.sh & TR-Server-Report.sh to "$s - "`host $s | cut -d " " -f5`"" .." && sshpass -p01Mar2019 scpadmin -o LogLevel=error $file1 $file2  $s:/var/tmp/

echo " "
echo "	Taking pre-checks in "$s - "`host $s | cut -d " " -f5`"" .." && sshpass -p01Mar2019 sshadmin $s -qtt "sudo bash -c 'export CRQ='"'$CRQ'"';

mkdir /root/PRE-$CRQ ;
/sbin/ifconfig -a |  tee  /root/PRE-$CRQ/ifconfig-$(date +%Y%m%d)  > /dev/null ;
mount |  tee /root/PRE-$CRQ/mount-$(date +%Y%m%d)  > /dev/null ;
cat /etc/fstab |  tee /root/PRE-$CRQ/fstab-$(date +%Y%m%d) > /dev/null ;
for i in `/sbin/ifconfig|grep eth|awk '\''{print $1}'\''`; do echo $i;  cat /etc/sysconfig/network-scripts/ifcfg-"$i" | egrep -i "device|hwaddr"; echo; done |  tee /root/PRE-$CRQ/ifcfg-eth-$(date +%Y%m%d)  > /dev/null ;
/sbin/route -n |  tee /root/PRE-$CRQ/route-$(date +%Y%m%d)  > /dev/null ;
for i in ` /sbin/ifconfig|grep eth|awk '\''{print $1}'\''`; do echo $i;  cat /etc/sysconfig/network-scripts/route-$i; echo; done |  tee /root/PRE-$CRQ/route-eth-$(date +%Y%m%d)  > /dev/null ;
ps auxwf |  tee /root/PRE-$CRQ/ps-$(date +%Y%m%d)  > /dev/null ;
/etc/init.d/monitor status |  tee /root/PRE-$CRQ/monitor-$(date +%Y%m%d)  > /dev/null ;
cat /etc/redhat-release |  tee /root/PRE-$CRQ/redhat-release-$(date +%Y%m%d)  > /dev/null ;
uname -a |  tee /root/PRE-$CRQ/uname-$(date +%Y%m%d)  > /dev/null ;
df -h |  tee /root/PRE-$CRQ/df-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/pvs |  tee /root/PRE-$CRQ/pvs-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/lvs |  tee /root/PRE-$CRQ/lvs-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/vgs |  tee /root/PRE-$CRQ/vgs-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/fdisk -l |  tee /root/PRE-$CRQ/fdisk_l-$(date +%Y%m%d)  > /dev/null ;
netstat -an |  tee /root/PRE-$CRQ/netstat-$(date +%Y%m%d)  > /dev/null ;
netstat -anp | egrep "14002|8101" |  tee /root/PRE-$CRQ/ADS-stat-$(date +%Y%m%d)  > /dev/null ;
/sbin/chkconfig --list |  tee /root/PRE-$CRQ/chkconfig-$(date +%Y%m%d)  > /dev/null ;
free -m | tee /root/PRE-$CRQ/swap-$(date +%Y%m%d)  > /dev/null ;
/sbin/hpasmcli -s "show server" |  tee /root/PRE-$CRQ/hpasmcli-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/hpssacli ctrl slot=0 show |  tee /root/PRE-$CRQ/hpssacli-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/hpssacli ctrl all show config detail |  tee /root/PRE-$CRQ/hpssacli-array-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/hpacucli ctrl slot=0 show |  tee /root/PRE-$CRQ/hpacucli-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/hpacucli ctrl all show config detail |  tee /root/PRE-$CRQ/hpacucli-array-$(date +%Y%m%d)  > /dev/null ;
/sbin/hponcfg -w /tmp/ilo |  tee /root/PRE-$CRQ/ilo-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/dmidecode --type 0 |  tee /root/PRE-$CRQ/bios-$(date +%Y%m%d)  > /dev/null ;
uptime | tee /root/PRE-$CRQ/uptime-$(date +%Y%m%d)  > /dev/null ;
/sbin/ip a | tee /root/PRE-$CRQ/ip-$(date +%Y%m%d)  > /dev/null ;
ntpstat |  tee /root/PRE-$CRQ/ntpstat-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/rhn-channel -l |  tee /root/PRE-$CRQ/rhn_channel-$(date +%Y%m%d)  > /dev/null ;
/usr/sbin/getenforce |  tee /root/PRE-$CRQ/getenforce-$(date +%Y%m%d)  > /dev/null ;
/sbin/service iptables status |  tee /root/PRE-$CRQ/iptables-$(date +%Y%m%d)  > /dev/null ;
cd /usr/local/svvs/home/svadmin;  ./TR-Server-Report.sh  |  tee /root/PRE-$CRQ/Server-Report-$(date +%Y%m%d)  > /dev/null ;
cd /var/tmp;  ./TR-Server-Report.sh  |  tee /root/PRE-$CRQ/Server-Report-1-$(date +%Y%m%d)  > /dev/null ;
for i in ` /sbin/ifconfig|grep eth|awk '\''{print $1}'\''`; do echo $i;  /sbin/ethtool $i  ; done |  tee /root/PRE-$CRQ/ethtool-eth-$(date +%Y%m%d)  > /dev/null ;
ls -d -C1 /sys/block/sd*/device/scsi_disk* |  tee /root/PRE-${CRQ}/scsi_disk-$(date +%Y%m%d)  > /dev/null ;
cat /proc/scsi/scsi |  tee /root/PRE-${CRQ}/proc-scsi-$(date +%Y%m%d)  > /dev/null ; 
/sbin/conrep -s -f /root/PRE-$CRQ/bios.dat-$(date +%Y%m%d) > /dev/null ; 
sh /var/tmp/bios_helper.sh -c -v |  tee /root/PRE-$CRQ/bios-check-$(date +%y%m%d) > /dev/null ; 
cd /usr/local/svvs/home/svadmin;  sh /bios_helper.sh -c -v |  tee -a /root/PRE-$CRQ/bios-check-1-$(date +%y%m%d) > /dev/null ; 

cp /etc/services /root/PRE-$CRQ/services-$(date +%Y%m%d);
cp /etc/sysctl.conf /root/PRE-$CRQ/sysctl.conf-$(date +%Y%m%d);
cp /etc/modprobe.conf /root/PRE-$CRQ/modprobe-$(date +%Y%m%d);
cp /etc/rc.local /root/PRE-$CRQ/rc.local-$(date +%Y%m%d);

echo "";
echo "Verifying pre-checks files" ;

ls -lrt /root/PRE-$CRQ/ ; 

echo ""' ;
echo """;

echo " "
echo "	Done Prechecks in "$s - "`host $s | cut -d " " -f5`"".."
echo " "
done

echo " "
echo "!!!	Pre-checks completed... Please proceed !!!"
# echo'; >> Checker_log_$CRQ 2>&1
echo ""


elif [ $ans == "2" ]

then
echo ""

# Reading CRQ Number
echo ""
read -p "	Please enter the CRQ number? : " CRQ 
echo ""

echo "	Started Post-checks ..."

for s in `cat hosts_list`
do
echo ""
echo "	Taking post-checks in "$s - "`host $s | cut -d " " -f5`"" .." && sshpass -p01Mar2019 sshadmin $s -qt  sudo -- -sh -c <<EOF
'export CRQ='"'$CRQ'"';
echo "" ; 

echo'; >> Checker_log_$CRQ 2>&1
EOF

echo " "
echo "	Done Post-checks in "$s - "`host $s | cut -d " " -f5`"".."
echo " "
done

echo "!!!	Post-checks completed !!! Please verify Checker_log_$CRQ ..."
echo " "

else 
echo " "
echo "	Please enter valid response..."
echo " "
exit 1


fi

#tail -f precheck_log_$CRQ
# End
